# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update_weight.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nn_config_pb2 as nn__config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='update_weight.proto',
  package='ddrl',
  syntax='proto3',
  serialized_pb=_b('\n\x13update_weight.proto\x12\x04\x64\x64rl\x1a\x0fnn_config.proto\"q\n\x0cmodel_weight\x12\x14\n\x0ctensor_index\x18\x01 \x01(\r\x12\r\n\x05n_dim\x18\x02 \x01(\r\x12\x0f\n\x07x_index\x18\x03 \x01(\r\x12\x0f\n\x07y_index\x18\x04 \x01(\r\x12\x0b\n\x03tau\x18\x05 \x01(\x02\x12\r\n\x05value\x18\x06 \x01(\x02\"\x86\x01\n\x13update_model_weight\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\tnn_config\x18\x02 \x01(\x0b\x32\x0f.ddrl.nn_config\x12\x19\n\x11n_tensor_in_model\x18\x03 \x01(\r\x12\"\n\x06weight\x18\x04 \x03(\x0b\x32\x12.ddrl.model_weightb\x06proto3')
  ,
  dependencies=[nn__config__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODEL_WEIGHT = _descriptor.Descriptor(
  name='model_weight',
  full_name='ddrl.model_weight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensor_index', full_name='ddrl.model_weight.tensor_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n_dim', full_name='ddrl.model_weight.n_dim', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x_index', full_name='ddrl.model_weight.x_index', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y_index', full_name='ddrl.model_weight.y_index', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tau', full_name='ddrl.model_weight.tau', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='ddrl.model_weight.value', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=159,
)


_UPDATE_MODEL_WEIGHT = _descriptor.Descriptor(
  name='update_model_weight',
  full_name='ddrl.update_model_weight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ddrl.update_model_weight.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nn_config', full_name='ddrl.update_model_weight.nn_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n_tensor_in_model', full_name='ddrl.update_model_weight.n_tensor_in_model', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='ddrl.update_model_weight.weight', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=296,
)

_UPDATE_MODEL_WEIGHT.fields_by_name['nn_config'].message_type = nn__config__pb2._NN_CONFIG
_UPDATE_MODEL_WEIGHT.fields_by_name['weight'].message_type = _MODEL_WEIGHT
DESCRIPTOR.message_types_by_name['model_weight'] = _MODEL_WEIGHT
DESCRIPTOR.message_types_by_name['update_model_weight'] = _UPDATE_MODEL_WEIGHT

model_weight = _reflection.GeneratedProtocolMessageType('model_weight', (_message.Message,), dict(
  DESCRIPTOR = _MODEL_WEIGHT,
  __module__ = 'update_weight_pb2'
  # @@protoc_insertion_point(class_scope:ddrl.model_weight)
  ))
_sym_db.RegisterMessage(model_weight)

update_model_weight = _reflection.GeneratedProtocolMessageType('update_model_weight', (_message.Message,), dict(
  DESCRIPTOR = _UPDATE_MODEL_WEIGHT,
  __module__ = 'update_weight_pb2'
  # @@protoc_insertion_point(class_scope:ddrl.update_model_weight)
  ))
_sym_db.RegisterMessage(update_model_weight)


# @@protoc_insertion_point(module_scope)
