// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ops_interface.proto

#ifndef PROTOBUF_ops_5finterface_2eproto__INCLUDED
#define PROTOBUF_ops_5finterface_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)

namespace ops {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ops_5finterface_2eproto();
void protobuf_AssignDesc_ops_5finterface_2eproto();
void protobuf_ShutdownFile_ops_5finterface_2eproto();

class ops_cell_conf;
class ops_input;
class ops_output;
class ops_ue_input;
class ops_ue_output;

// ===================================================================

class ops_cell_conf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ops.ops_cell_conf) */ {
 public:
  ops_cell_conf();
  virtual ~ops_cell_conf();

  ops_cell_conf(const ops_cell_conf& from);

  inline ops_cell_conf& operator=(const ops_cell_conf& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ops_cell_conf& default_instance();

  void Swap(ops_cell_conf* other);

  // implements Message ----------------------------------------------

  inline ops_cell_conf* New() const { return New(NULL); }

  ops_cell_conf* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ops_cell_conf& from);
  void MergeFrom(const ops_cell_conf& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ops_cell_conf* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 cell_id = 1;
  void clear_cell_id();
  static const int kCellIdFieldNumber = 1;
  ::google::protobuf::uint32 cell_id() const;
  void set_cell_id(::google::protobuf::uint32 value);

  // optional uint32 n_prb = 2;
  void clear_n_prb();
  static const int kNPrbFieldNumber = 2;
  ::google::protobuf::uint32 n_prb() const;
  void set_n_prb(::google::protobuf::uint32 value);

  // optional uint32 tti_duration = 3;
  void clear_tti_duration();
  static const int kTtiDurationFieldNumber = 3;
  ::google::protobuf::uint32 tti_duration() const;
  void set_tti_duration(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ops.ops_cell_conf)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 cell_id_;
  ::google::protobuf::uint32 n_prb_;
  ::google::protobuf::uint32 tti_duration_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ops_5finterface_2eproto();
  friend void protobuf_AssignDesc_ops_5finterface_2eproto();
  friend void protobuf_ShutdownFile_ops_5finterface_2eproto();

  void InitAsDefaultInstance();
  static ops_cell_conf* default_instance_;
};
// -------------------------------------------------------------------

class ops_ue_input : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ops.ops_ue_input) */ {
 public:
  ops_ue_input();
  virtual ~ops_ue_input();

  ops_ue_input(const ops_ue_input& from);

  inline ops_ue_input& operator=(const ops_ue_input& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ops_ue_input& default_instance();

  void Swap(ops_ue_input* other);

  // implements Message ----------------------------------------------

  inline ops_ue_input* New() const { return New(NULL); }

  ops_ue_input* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ops_ue_input& from);
  void MergeFrom(const ops_ue_input& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ops_ue_input* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 rnti = 1;
  void clear_rnti();
  static const int kRntiFieldNumber = 1;
  ::google::protobuf::uint32 rnti() const;
  void set_rnti(::google::protobuf::uint32 value);

  // optional .google.protobuf.Timestamp hts = 2;
  bool has_hts() const;
  void clear_hts();
  static const int kHtsFieldNumber = 2;
  const ::google::protobuf::Timestamp& hts() const;
  ::google::protobuf::Timestamp* mutable_hts();
  ::google::protobuf::Timestamp* release_hts();
  void set_allocated_hts(::google::protobuf::Timestamp* hts);

  // optional float alpha = 3;
  void clear_alpha();
  static const int kAlphaFieldNumber = 3;
  float alpha() const;
  void set_alpha(float value);

  // @@protoc_insertion_point(class_scope:ops.ops_ue_input)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::Timestamp* hts_;
  ::google::protobuf::uint32 rnti_;
  float alpha_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ops_5finterface_2eproto();
  friend void protobuf_AssignDesc_ops_5finterface_2eproto();
  friend void protobuf_ShutdownFile_ops_5finterface_2eproto();

  void InitAsDefaultInstance();
  static ops_ue_input* default_instance_;
};
// -------------------------------------------------------------------

class ops_input : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ops.ops_input) */ {
 public:
  ops_input();
  virtual ~ops_input();

  ops_input(const ops_input& from);

  inline ops_input& operator=(const ops_input& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ops_input& default_instance();

  void Swap(ops_input* other);

  // implements Message ----------------------------------------------

  inline ops_input* New() const { return New(NULL); }

  ops_input* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ops_input& from);
  void MergeFrom(const ops_input& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ops_input* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 tti = 1;
  void clear_tti();
  static const int kTtiFieldNumber = 1;
  ::google::protobuf::uint64 tti() const;
  void set_tti(::google::protobuf::uint64 value);

  // repeated .ops.ops_ue_input ue_input = 2;
  int ue_input_size() const;
  void clear_ue_input();
  static const int kUeInputFieldNumber = 2;
  const ::ops::ops_ue_input& ue_input(int index) const;
  ::ops::ops_ue_input* mutable_ue_input(int index);
  ::ops::ops_ue_input* add_ue_input();
  ::google::protobuf::RepeatedPtrField< ::ops::ops_ue_input >*
      mutable_ue_input();
  const ::google::protobuf::RepeatedPtrField< ::ops::ops_ue_input >&
      ue_input() const;

  // @@protoc_insertion_point(class_scope:ops.ops_input)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 tti_;
  ::google::protobuf::RepeatedPtrField< ::ops::ops_ue_input > ue_input_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ops_5finterface_2eproto();
  friend void protobuf_AssignDesc_ops_5finterface_2eproto();
  friend void protobuf_ShutdownFile_ops_5finterface_2eproto();

  void InitAsDefaultInstance();
  static ops_input* default_instance_;
};
// -------------------------------------------------------------------

class ops_ue_output : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ops.ops_ue_output) */ {
 public:
  ops_ue_output();
  virtual ~ops_ue_output();

  ops_ue_output(const ops_ue_output& from);

  inline ops_ue_output& operator=(const ops_ue_output& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ops_ue_output& default_instance();

  void Swap(ops_ue_output* other);

  // implements Message ----------------------------------------------

  inline ops_ue_output* New() const { return New(NULL); }

  ops_ue_output* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ops_ue_output& from);
  void MergeFrom(const ops_ue_output& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ops_ue_output* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 rnti = 1;
  void clear_rnti();
  static const int kRntiFieldNumber = 1;
  ::google::protobuf::uint32 rnti() const;
  void set_rnti(::google::protobuf::uint32 value);

  // optional bool tx = 2;
  void clear_tx();
  static const int kTxFieldNumber = 2;
  bool tx() const;
  void set_tx(bool value);

  // @@protoc_insertion_point(class_scope:ops.ops_ue_output)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 rnti_;
  bool tx_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ops_5finterface_2eproto();
  friend void protobuf_AssignDesc_ops_5finterface_2eproto();
  friend void protobuf_ShutdownFile_ops_5finterface_2eproto();

  void InitAsDefaultInstance();
  static ops_ue_output* default_instance_;
};
// -------------------------------------------------------------------

class ops_output : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ops.ops_output) */ {
 public:
  ops_output();
  virtual ~ops_output();

  ops_output(const ops_output& from);

  inline ops_output& operator=(const ops_output& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ops_output& default_instance();

  void Swap(ops_output* other);

  // implements Message ----------------------------------------------

  inline ops_output* New() const { return New(NULL); }

  ops_output* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ops_output& from);
  void MergeFrom(const ops_output& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ops_output* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 tti = 1;
  void clear_tti();
  static const int kTtiFieldNumber = 1;
  ::google::protobuf::uint64 tti() const;
  void set_tti(::google::protobuf::uint64 value);

  // repeated .ops.ops_ue_output ue_output = 2;
  int ue_output_size() const;
  void clear_ue_output();
  static const int kUeOutputFieldNumber = 2;
  const ::ops::ops_ue_output& ue_output(int index) const;
  ::ops::ops_ue_output* mutable_ue_output(int index);
  ::ops::ops_ue_output* add_ue_output();
  ::google::protobuf::RepeatedPtrField< ::ops::ops_ue_output >*
      mutable_ue_output();
  const ::google::protobuf::RepeatedPtrField< ::ops::ops_ue_output >&
      ue_output() const;

  // @@protoc_insertion_point(class_scope:ops.ops_output)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 tti_;
  ::google::protobuf::RepeatedPtrField< ::ops::ops_ue_output > ue_output_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ops_5finterface_2eproto();
  friend void protobuf_AssignDesc_ops_5finterface_2eproto();
  friend void protobuf_ShutdownFile_ops_5finterface_2eproto();

  void InitAsDefaultInstance();
  static ops_output* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ops_cell_conf

// optional uint32 cell_id = 1;
inline void ops_cell_conf::clear_cell_id() {
  cell_id_ = 0u;
}
inline ::google::protobuf::uint32 ops_cell_conf::cell_id() const {
  // @@protoc_insertion_point(field_get:ops.ops_cell_conf.cell_id)
  return cell_id_;
}
inline void ops_cell_conf::set_cell_id(::google::protobuf::uint32 value) {
  
  cell_id_ = value;
  // @@protoc_insertion_point(field_set:ops.ops_cell_conf.cell_id)
}

// optional uint32 n_prb = 2;
inline void ops_cell_conf::clear_n_prb() {
  n_prb_ = 0u;
}
inline ::google::protobuf::uint32 ops_cell_conf::n_prb() const {
  // @@protoc_insertion_point(field_get:ops.ops_cell_conf.n_prb)
  return n_prb_;
}
inline void ops_cell_conf::set_n_prb(::google::protobuf::uint32 value) {
  
  n_prb_ = value;
  // @@protoc_insertion_point(field_set:ops.ops_cell_conf.n_prb)
}

// optional uint32 tti_duration = 3;
inline void ops_cell_conf::clear_tti_duration() {
  tti_duration_ = 0u;
}
inline ::google::protobuf::uint32 ops_cell_conf::tti_duration() const {
  // @@protoc_insertion_point(field_get:ops.ops_cell_conf.tti_duration)
  return tti_duration_;
}
inline void ops_cell_conf::set_tti_duration(::google::protobuf::uint32 value) {
  
  tti_duration_ = value;
  // @@protoc_insertion_point(field_set:ops.ops_cell_conf.tti_duration)
}

// -------------------------------------------------------------------

// ops_ue_input

// optional uint32 rnti = 1;
inline void ops_ue_input::clear_rnti() {
  rnti_ = 0u;
}
inline ::google::protobuf::uint32 ops_ue_input::rnti() const {
  // @@protoc_insertion_point(field_get:ops.ops_ue_input.rnti)
  return rnti_;
}
inline void ops_ue_input::set_rnti(::google::protobuf::uint32 value) {
  
  rnti_ = value;
  // @@protoc_insertion_point(field_set:ops.ops_ue_input.rnti)
}

// optional .google.protobuf.Timestamp hts = 2;
inline bool ops_ue_input::has_hts() const {
  return !_is_default_instance_ && hts_ != NULL;
}
inline void ops_ue_input::clear_hts() {
  if (GetArenaNoVirtual() == NULL && hts_ != NULL) delete hts_;
  hts_ = NULL;
}
inline const ::google::protobuf::Timestamp& ops_ue_input::hts() const {
  // @@protoc_insertion_point(field_get:ops.ops_ue_input.hts)
  return hts_ != NULL ? *hts_ : *default_instance_->hts_;
}
inline ::google::protobuf::Timestamp* ops_ue_input::mutable_hts() {
  
  if (hts_ == NULL) {
    hts_ = new ::google::protobuf::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:ops.ops_ue_input.hts)
  return hts_;
}
inline ::google::protobuf::Timestamp* ops_ue_input::release_hts() {
  // @@protoc_insertion_point(field_release:ops.ops_ue_input.hts)
  
  ::google::protobuf::Timestamp* temp = hts_;
  hts_ = NULL;
  return temp;
}
inline void ops_ue_input::set_allocated_hts(::google::protobuf::Timestamp* hts) {
  delete hts_;
  if (hts != NULL && hts->GetArena() != NULL) {
    ::google::protobuf::Timestamp* new_hts = new ::google::protobuf::Timestamp;
    new_hts->CopyFrom(*hts);
    hts = new_hts;
  }
  hts_ = hts;
  if (hts) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:ops.ops_ue_input.hts)
}

// optional float alpha = 3;
inline void ops_ue_input::clear_alpha() {
  alpha_ = 0;
}
inline float ops_ue_input::alpha() const {
  // @@protoc_insertion_point(field_get:ops.ops_ue_input.alpha)
  return alpha_;
}
inline void ops_ue_input::set_alpha(float value) {
  
  alpha_ = value;
  // @@protoc_insertion_point(field_set:ops.ops_ue_input.alpha)
}

// -------------------------------------------------------------------

// ops_input

// optional uint64 tti = 1;
inline void ops_input::clear_tti() {
  tti_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ops_input::tti() const {
  // @@protoc_insertion_point(field_get:ops.ops_input.tti)
  return tti_;
}
inline void ops_input::set_tti(::google::protobuf::uint64 value) {
  
  tti_ = value;
  // @@protoc_insertion_point(field_set:ops.ops_input.tti)
}

// repeated .ops.ops_ue_input ue_input = 2;
inline int ops_input::ue_input_size() const {
  return ue_input_.size();
}
inline void ops_input::clear_ue_input() {
  ue_input_.Clear();
}
inline const ::ops::ops_ue_input& ops_input::ue_input(int index) const {
  // @@protoc_insertion_point(field_get:ops.ops_input.ue_input)
  return ue_input_.Get(index);
}
inline ::ops::ops_ue_input* ops_input::mutable_ue_input(int index) {
  // @@protoc_insertion_point(field_mutable:ops.ops_input.ue_input)
  return ue_input_.Mutable(index);
}
inline ::ops::ops_ue_input* ops_input::add_ue_input() {
  // @@protoc_insertion_point(field_add:ops.ops_input.ue_input)
  return ue_input_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ops::ops_ue_input >*
ops_input::mutable_ue_input() {
  // @@protoc_insertion_point(field_mutable_list:ops.ops_input.ue_input)
  return &ue_input_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ops::ops_ue_input >&
ops_input::ue_input() const {
  // @@protoc_insertion_point(field_list:ops.ops_input.ue_input)
  return ue_input_;
}

// -------------------------------------------------------------------

// ops_ue_output

// optional uint32 rnti = 1;
inline void ops_ue_output::clear_rnti() {
  rnti_ = 0u;
}
inline ::google::protobuf::uint32 ops_ue_output::rnti() const {
  // @@protoc_insertion_point(field_get:ops.ops_ue_output.rnti)
  return rnti_;
}
inline void ops_ue_output::set_rnti(::google::protobuf::uint32 value) {
  
  rnti_ = value;
  // @@protoc_insertion_point(field_set:ops.ops_ue_output.rnti)
}

// optional bool tx = 2;
inline void ops_ue_output::clear_tx() {
  tx_ = false;
}
inline bool ops_ue_output::tx() const {
  // @@protoc_insertion_point(field_get:ops.ops_ue_output.tx)
  return tx_;
}
inline void ops_ue_output::set_tx(bool value) {
  
  tx_ = value;
  // @@protoc_insertion_point(field_set:ops.ops_ue_output.tx)
}

// -------------------------------------------------------------------

// ops_output

// optional uint64 tti = 1;
inline void ops_output::clear_tti() {
  tti_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ops_output::tti() const {
  // @@protoc_insertion_point(field_get:ops.ops_output.tti)
  return tti_;
}
inline void ops_output::set_tti(::google::protobuf::uint64 value) {
  
  tti_ = value;
  // @@protoc_insertion_point(field_set:ops.ops_output.tti)
}

// repeated .ops.ops_ue_output ue_output = 2;
inline int ops_output::ue_output_size() const {
  return ue_output_.size();
}
inline void ops_output::clear_ue_output() {
  ue_output_.Clear();
}
inline const ::ops::ops_ue_output& ops_output::ue_output(int index) const {
  // @@protoc_insertion_point(field_get:ops.ops_output.ue_output)
  return ue_output_.Get(index);
}
inline ::ops::ops_ue_output* ops_output::mutable_ue_output(int index) {
  // @@protoc_insertion_point(field_mutable:ops.ops_output.ue_output)
  return ue_output_.Mutable(index);
}
inline ::ops::ops_ue_output* ops_output::add_ue_output() {
  // @@protoc_insertion_point(field_add:ops.ops_output.ue_output)
  return ue_output_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ops::ops_ue_output >*
ops_output::mutable_ue_output() {
  // @@protoc_insertion_point(field_mutable_list:ops.ops_output.ue_output)
  return &ue_output_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ops::ops_ue_output >&
ops_output::ue_output() const {
  // @@protoc_insertion_point(field_list:ops.ops_output.ue_output)
  return ue_output_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ops

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ops_5finterface_2eproto__INCLUDED
