# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nn_config.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nn_config.proto',
  package='ddrl',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fnn_config.proto\x12\x04\x64\x64rl\"\x8c\x01\n\tnn_config\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07nn_arch\x18\x02 \x03(\r\x12*\n\taf_config\x18\x03 \x03(\x0e\x32\x17.ddrl.nn_config.af_type\"4\n\x07\x61\x66_type\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04RELU\x10\x01\x12\x0b\n\x07SIGMOID\x10\x02\x12\x08\n\x04TANH\x10\x03\x62\x06proto3'
)



_NN_CONFIG_AF_TYPE = _descriptor.EnumDescriptor(
  name='af_type',
  full_name='ddrl.nn_config.af_type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RELU', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SIGMOID', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TANH', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=114,
  serialized_end=166,
)
_sym_db.RegisterEnumDescriptor(_NN_CONFIG_AF_TYPE)


_NN_CONFIG = _descriptor.Descriptor(
  name='nn_config',
  full_name='ddrl.nn_config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ddrl.nn_config.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nn_arch', full_name='ddrl.nn_config.nn_arch', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='af_config', full_name='ddrl.nn_config.af_config', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NN_CONFIG_AF_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=166,
)

_NN_CONFIG.fields_by_name['af_config'].enum_type = _NN_CONFIG_AF_TYPE
_NN_CONFIG_AF_TYPE.containing_type = _NN_CONFIG
DESCRIPTOR.message_types_by_name['nn_config'] = _NN_CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

nn_config = _reflection.GeneratedProtocolMessageType('nn_config', (_message.Message,), {
  'DESCRIPTOR' : _NN_CONFIG,
  '__module__' : 'nn_config_pb2'
  # @@protoc_insertion_point(class_scope:ddrl.nn_config)
  })
_sym_db.RegisterMessage(nn_config)


# @@protoc_insertion_point(module_scope)
